### ISSUE TITLE
Format fst does not preserve data.table class

### ISSUE THREAD

**Issue by vkehayas** [ropensci/drake#998] opened 2019-08-28 09:56 UTC
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

Before the `fst` format was available I had no problem using `data.table` objects as targets in my drake plans.
But if I use the `fst` format and then try to load the `data.table` object, it loses its class, reverting to `data.frame`.
However, as far as I understand, the `fst` package provides the option to load an object as `data.table` (option `as.data.table` in `read_fst`: https://cran.r-project.org/web/packages/fst/fst.pdf, p8). Would you consider to allow the user passing this argument through `loadd` and `readd`? Or is there another workaround that I am not seeing, other than re-assigning the class to the object each time after I load it?

Here is a minimal reproducible example:

```r
library(fst)
library(drake)
library(data.table)

drakePlan = drake_plan(
  dataFrame = expand.grid(x = rnorm(10),
                          y = runif(10)),
  dataTable = as.data.table(dataFrame)
)

make(drakePlan)

## target dataFrame

## target dataTable

loadd(dataFrame)
class(dataFrame)

## [1] "data.frame"

loadd(dataTable)
class(dataTable)

## [1] "data.table" "data.frame"

fstPlan = drakePlan
fstPlan$format = "fst"
clean()
make(fstPlan)

## Unloading targets from environment:
##   dataFrame
##   dataTable

## target dataFrame

## target dataTable

loadd(dataTable)
class(dataTable)

## [1] "data.frame"

```

**Comment by vkehayas** [comment] 2019-08-28 10:31
Another more important issue, other than `loadd`ing and `readd`ing, is what happens when the targets that are used in other steps of the plan are assumed to be of `data.table` class as they were created as such. Right now I have a very large plan (10.000s of lines) in which I selectively converted the `data.table` (and hence `data.frame`) class targets to the `fst` format thinking that it will benefit performance, only to realise that the targets were stripped of their `data.table` class.

```r
largePlan = rbind(fstPlan,
                  drake_plan(
                    # A line displaying idiomatic use of a data.table
                    target(summaryTarget = dataTable[, meanX := mean(x)],
                           format = "fst"))
)
```
I guess for this to be solved either `drake` needs to keep track of the object's class, or I should stop using the `fst` format for `data.table` objects.

**Comment by vkehayas** [comment] 2019-08-28 13:54
No problem, thanks for acknowledging.

**Comment by vkehayas** [comment] 2019-08-28 20:39
Sounds good to me, thanks. It's certainly my fault that I did not read the `fst` documentation carefully enough to understand that only the `data.frame` class will be kept (or test before deploying), but a note in `drake`'s docs will be appreciated. Let me know if you'd like me to take a stab at it if you cannot find the time, in which case I may just need some guidance on what needs to be done.

**Comment by MarcusKlik** [comment] 2019-08-29 10:02
Hi @vkehayas, I understand it would be convenient in this case for `fst` to retain the specific table type (_tibble_, _data.frame_ or _data.table_) but the problem is that the _fst_ format is a language agnostic format and these table types have no meaning outside `R`...

Indeed, using a _fst_dt_ format is probably the next best solution!

**Comment by wlandau** [comment] 2019-08-30 03:42
I gave some more thought to making `drake`'s existing `fst` format handle `data.table`s, `tibble`s, and all other kinds of data frames seamlessly. To do this, we need to restore all the attributes of a target when we load it in a new R session. However, we cannot expect all the attributes to stay valid from session to session. For example, each `data.table` object has an `.internal.selfref` pointer. If `drake` tries to restore the old pointer and then use the object, the R session would probably segfault.

``` r
library(data.table)
x <- as.data.table(mtcars)
attributes(x)
#> $names
#>  [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
#> [11] "carb"
#> 
#> $row.names
#>  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
#> [24] 24 25 26 27 28 29 30 31 32
#> 
#> $class
#> [1] "data.table" "data.frame"
#> 
#> $.internal.selfref
#> <pointer: 0x7fd1f00052e0>
```

<sup>Created on 2019-08-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Sufficient to complete this issue:

- [ ] Add and document a new "fst_dt" format.
- [ ] For the "fst" format, call `as.data.frame()` on the return value before assigning it to memory. We need to make sure targets in memory match targets in storage.

**Comment by wlandau** [comment] 2019-08-30 04:33
In fact, let's force "fst" targets using `as.data.frame()` and "fst_dt" targets using `as.data.table()` for both memory and storage.

**Comment by wlandau** [comment] 2019-08-30 05:02
@MarcusKlik, has `read_fst` always supported an `as.data.table` argument? I am wondering if I should require a minimum version of `fst` in `drake`'s `DESCRIPTION`.

**Comment by fstpackage** [comment] 2019-08-30 22:04
Hi @wlandau, yes it has! At least for all the versions available from CRAN anyway :-).

Even if you use `as.data.table()` you should definitely use the `as.data.table` argument in `read_fst()` as well to avoid unnecessary copies:

``` r
# create data.frame and trace column
x <- data.frame(X = 1:10)
tracemem(x$X)
#> [1] "<00000000153A2900>"

# convert to data.table (column copied!)
y <- data.table::as.data.table(x)
tracemem(y$X)
#> [1] "<0000000017FE2FC0>"
```

so if you convert after reading a _data.frame_ all column vectors will be copied and that will take a bite out of the performance...

**Comment by fstpackage** [comment] 2019-08-30 22:09
Or you could use `data.table::setDT()` to avoid that:

``` r
# create data.frame and trace column and table
x <- data.frame(X = 1:10)

# convert to data.table (column not copied)
y <- data.table::setDT(x)

# columns have identical pointers
tracemem(x$X)
#> [1] "<00000000120F9688>"
tracemem(y$X)
#> [1] "<00000000120F9688>"
```

**Comment by wlandau** [comment] 2019-08-30 22:24
Thanks, I did not know about `setDT()`. The current "fst_dt" format uses `read_fst(as.data.table = TRUE)` rather than `as.data.table()`. I did notice the `copy()` inside the latter.

**Comment by vkehayas** [comment] 2019-09-02 08:25
Thanks for the feature @wlandau. I encountered another `fst`-related issue - not sure if it's worth opening a new issue here but it surfaced while using the `fst_dt` format.

When a target of an `fst_dt` plan returns `NULL`, `drake` through `fst` returns the following error:

```
Error in fst::write_fst(x = value$value, path = tmp) : 
  Your dataset needs at least one column.
Calls: source ... dcst_set -> dcst_set.drake_format_fst_dt -> <Anonymous>
```

Would it be fit for `drake`'s purposes to skip the `fst::write_fst` step if the target is `NULL`?

**Comment by wlandau** [comment] 2019-09-02 16:26
Sure. In general,  we should drop any kind of format for NULL values. For typed empty values like character(0), however, I think that is a user error.

**Closed** 2019-09-03 04:13 UTC
Labels: topic: api

**Comment by kendonB** [comment] 2019-12-10 18:47
Just coming across this. Is it possible to do something simple for `tbl_df` and have drake remember what the user tried to save it as and to just cast it upon reading using `tibble::as_tibble`?

**Comment by wlandau** [comment] 2019-12-11 01:39
I thought about this, but decided against it. Saving, loading, and target invalidation would get messier and more error prone if we did that. I think the current behavior is safer: coerce the target into a compatible type and warn the user what is happening.

**Comment by vkehayas** [comment] 2020-02-13 11:12
Hi Will!

I started getting the error about `NULL` values with the `fst_dt` format again:

```r
plan = drake_plan(
    x = target(data.table(NULL),
               format = "fst_dt")
)
make(plan)
```
```
target x
Error in fst::write_fst(x = value$value, path = tmp) : 
  Your dataset needs at least one column.
```
I couldn't see anything obvious in [`assign_format`](https://github.com/ropensci/drake/blob/master/R/local_build.R#L330-343) that could cause this.

```r
sessionInfo()
```
```
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_IE.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_IE.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_IE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_IE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] qs_0.21.1          cowplot_1.0.0      bookdown_0.14      ggplot2_3.2.1      igraph_1.2.4.1     matrixStats_0.54.0 Rfast_1.9.5        RcppZiggurat_0.1.5
 [9] Rcpp_1.0.2         data.table_1.12.6  matlabr_1.5.2      future.apply_1.3.0 future_1.14.0      drake_7.10.0       fst_0.9.0         

loaded via a namespace (and not attached):
 [1] storr_1.2.1         tidyselect_0.2.5    xfun_0.8            purrr_0.3.2         listenv_0.7.0       colorspace_1.4-1    vctrs_0.2.0        
 [8] htmltools_0.3.6     yaml_2.2.0          rlang_0.4.0         pillar_1.4.2        txtq_0.2.0          glue_1.3.1          withr_2.1.2        
[15] stringr_1.4.0       munsell_0.5.0       gtable_0.3.0        codetools_0.2-16    evaluate_0.14       RApiSerialize_0.1.0 knitr_1.25         
[22] parallel_3.6.2      backports_1.1.5     scales_1.0.0        filelock_1.0.2      packrat_0.5.0       digest_0.6.22       stringi_1.4.3      
[29] dplyr_0.8.3         grid_3.6.2          tools_3.6.2         magrittr_1.5        base64url_1.4       lazyeval_0.2.2      tibble_2.1.3       
[36] crayon_1.3.4        pkgconfig_2.0.3     zeallot_0.1.0       assertthat_0.2.1    rmarkdown_1.16      rstudioapi_0.10     R6_2.4.0     
```

**Comment by wlandau** [comment] 2020-02-13 13:30
`drake` handles regular `NULL`, the general case, but not `data.table(NULL)`, a special case. It appears to be a limitation of `fst`:

```r
fst::write_fst(data.table(NULL), tempfile())
#> Error in fst::write_fst(data.table(NULL), tempfile()) : 
#>   Your dataset needs at least one column.
```

I recommend handling this yourself with custom functions.

```r
dt_val <- function(dt) {
  if (ncol(dt) < 1L) {
    dt <- data.table(NA)
  }
  dt
}

drake_plan(x = target(dt_val(your_dt), format = "fst_dt"))
```

**Comment by wlandau** [comment] 2020-02-13 13:31
By the way, @kendonB, there is now a new `"fst_tbl"` formt for `tibble`s.
