### ISSUE TITLE
Bare-bones scheduling and caching

### ISSUE THREAD

**Issue by krlmlr** [ropensci/drake#575] opened 2018-11-07 10:16 UTC
For some use cases of _drake_, I'd rather just supply the dependency graph, the commands (as quosures or perhaps [crates](https://cran.r-project.org/web/packages/carrier/index.html)), and a list of targets to build. I would expect _drake_ to take care of

- caching and retrieving objects, making them available for the expression/function
- topological sorting, scheduling and running the code
- live updates of the dependency graph and of the targets to be built (later, for #304)

but really not more. This will remove all overhead from analyzing the expressions, leaving it to a higher level in the API and perhaps other frontend packages.

I believe that separation along these lines may help the overall architecture, and eventually lead to a clean separation into the _workers_ package -- as a first step a lower-level API (perhaps with a distinct prefix) would do the job.

I've seen hasty parallelism, my proposal feels like hasty plus object storage minus parsing. Does that make sense?

**Comment by wlandau** [comment] 2018-11-07 22:56
I like the idea. Do you think we can pilot it from within hasty mode first? Object storage is just a matter of supplying the right `hasty_build` function to `make()` (see `default_hasty_build()`).

And I like your plan for `workers`. I was planning to move hasty mode there eventually, and I think it is worth seeing how bare-bones caching/scheduling plays out in `drake` itself.

As pre-work for live updates to the dependency graph, I am reopening #440. Supplying a graph and cleaning up the architecture will be much simpler if the graph does not need special attributes. (The current behavior is to generate an `igraph` of jobs and attach more verbose dependency information to the nodes.) My current thinking is to have the following major data structures:

- The workflow plan data frame with dependencies *implicitly* specified.
- The lookup structure from #440 with the dependencies *explicitly* specified as in a `Makefile` (and listed by type: targets, files, dependencies from triggers, etc.) I am thinking this lookup structure (name pending) should be the direct outcome of the code analysis. Each element should be like one of the objects returned from `deps_target()`.
- A simple `igraph` of jobs.
- A priority queue.

My major development goals for `drake` right now are to reduce overhead and simplify the architecture, both for bare-bones execution and the rest of the package.

**Comment by wlandau** [comment] 2018-11-08 01:44
> Are you suggesting to expose an API to manually construct the lookup structure? 

You can take credit for that suggestion. As a first step, I was only planning to implement the lookup structure internally. Over the course of development, I found that I needed to know things about the code analysis that I could not get from the graph. As hotfixes piled up, the graph's attributes got stranger and more complicated. So I think we need the lookup as an intermediate structure between the plan and the graph, with the sole purpose of containing the code analysis results in full detail.

> Would that be lower-level, higher-level, or orthogonal to `drake_config()`?

I was thinking we could generate this structure as one of the steps of `drake_config()` and keep track of it in `config$lookup` (Again, name pending. I am open to suggestions.)

> Do we get a new lower-level make() function that operates on this lookup structure, which would perhaps allow us to avoid tweaking the hasty_build argument?

I am not sure, but I hope so. It might let us skip the graph and go straight to the priority queue. That, along with improvements to the priority queue itself, could open up the dynamic build decisions you proposed in #233 and #304. It would be great to solve #561 first because the requisite refactoring will be much easier without so many parallel backends.

**Comment by wlandau** [comment] 2018-11-08 04:41
A couple remarks:

- I started work on #440 [here](https://github.com/ropensci/drake/tree/440), mainly in `create_drake_nodes.R` and `create_drake_graph.R`. I am super excited about all this refactoring, the code will be sorter and in much better shape afterwards. However, I am booked most of this week, and I go on vacation Nov 15-27, so I am unlikely to finish it anytime soon.
- I forgot to mention: you can already supply a `graph` argument to `make()`, but right now, but because of the strange attributes I am trying to get rid of, users need to use a graph already generated by `drake_config()`.

**Comment by wlandau** [comment] 2018-11-16 14:55
How about the name, config$outline?

**Comment by krlmlr** [comment] 2018-11-16 15:10
Not sure. Do we have a glossary of terms like dependency, graph, schedule, ...? We can think of a name that fits existing names.

In my example above, `a` is a prerequisite to `b`.

I think we still need both incoming and outgoing edges. Building `a` (and any other prerequisite of `b`) runs decrease-key on `b` (so we need `a - b`), but `b` needs to be initialized with the number of prerequisites to `b` (we need at least `length(b - *)`). Why not just expect a proper subgraph of the dependency graph: if `a` and `b` are part of the subgraph, edges between them are included iff they are part of the full dependency graph.

**Comment by wlandau** [comment] 2018-11-16 18:46
> Not sure. Do we have a glossary of terms like dependency, graph, schedule, ...? We can think of a name that fits existing names.

A glossary sounds like a great step towards the formal design spec I should have written from the beginning. The closest existing materials I can think of are the [arguments to `drake_config()`](https://github.com/ropensci/drake/blob/d66d1c57833cf415c5024c97fa1165ecc049abb4/R/config.R#L20-L406), the [list elements returned from `drake_config()`](https://github.com/ropensci/drake/blob/d66d1c57833cf415c5024c97fa1165ecc049abb4/R/config.R#L542-L587), the list elements returned from [`drake_meta()`](https://github.com/ropensci/drake/blob/d66d1c57833cf415c5024c97fa1165ecc049abb4/R/meta.R#L48), and the [`storr` namespaces](https://github.com/ropensci/drake/blob/master/R/cache_namespaces.R).

My personal opinion is that "outline" is compatible with the other names, and it looks and feels like an outline in the same way that a `Makefile` does. My biggest concern is that it is not evocative of the function in the same way "ordinances" or "dependency registry" or "low-level plan" or "more detailed plan" would be.

> I think we still need both incoming and outgoing edges. Building a (and any other prerequisite of b) runs decrease-key on b (so we need a - b), but b needs to be initialized with the number of prerequisites to b (we need at least length(b - *)). Why not just expect a proper subgraph of the dependency graph: if a and b are part of the subgraph, edges between them are included iff they are part of the full dependency graph.

Yeah, I agree now. If we decentralize the full graph, we should probably work with the subgraphs with incoming and outgoing edges. I am not yet sure if/when this will become enough of a priority for implementation.

**Comment by wlandau** [comment] 2018-11-21 15:01
Moving the discussions of word choice for config$ordinances to #440.

**Comment by wlandau** [comment] 2018-11-21 15:04
See https://github.com/ropensci/drake/issues/440#issuecomment-440695271

**Comment by wlandau** [comment] 2018-12-17 12:45
For any functionality not already available through `make(parallelism = "hasty", hasty_build = ...)`, I would prefer to delay the implementation until after #561 and the release of version 7.0.0.

**Comment by wlandau** [comment] 2019-01-04 02:54
Update: it is now possible to supply a custom scheduler function to the `parallelism` argument of `make()` for the purposes of experimentation. Examples: https://github.com/wlandau/drake.hasty (an intentional sandbox) and https://github.com/wlandau/drake.future.lapply.staged (deprecated functionality that @kendonB still needs). Both are very small. Because of the use of `:::`, neither will ever get to CRAN, but that's okay.

**Comment by wlandau** [comment] 2019-01-05 18:01
@krlmlr, would you take a look at the [`drake.hasty`](https://github.com/wlandau/drake.hasty) package? I do not plan to release it to CRAN, but I still think it solves this issue (except for #304, which should be a [`drake.hasty`](https://github.com/wlandau/drake.hasty) issue with the time comes).

``` r
library(drake.hasty) # https://github.com/wlandau/drake.hasty
#> Loading required package: drake
plan <- drake_plan(x = rnorm(100), y = mean(x), z = median(x))

# In addition to the graph, we also need other parts of the config object,
# such as the layout and the prework (memory management, packages, etc.).
config <- drake_config(plan, parallelism = backend_hasty)

# Optionally activate clustermq for scheduling.
# (Otherwise, just run targets in a loop in topological order.)
config$jobs <- 2
options(clustermq.scheduler = "multicore")

# For each target, tell drake to run the command,
# store the value, and do nothing else.
config$hasty_build <- hasty_build_store

# Run the project.
make(config = config)
#> Warning: `drake` can indeed accept a custom scheduler function for the
#> `parallelism` argument of `make()` but this is only for the sake of
#> experimentation and graceful deprecation. Your own custom schedulers may
#> cause surprising errors. Use at your own risk.
#> Warning: Hasty mode THROWS AWAY REPRODUCIBILITY to gain speed.
#> drake's scientific claims at
#>   https://ropensci.github.io/drake/#reproducibility-with-confidence
#>   are NOT VALID IN HASTY MODE!
#> Targets could be out of date even after make(),
#>   and you have no way of knowing.
#> USE AT YOUR OWN RISK!
#> Details: https://ropenscilabs.github.io/drake-manual/hpc.html#hasty-mode
#> Submitting 2 worker jobs (ID: 7546) ...
#> target x
#> target y
#> target z
#> Master: [0.2s 18.6% CPU]; Worker: [avg 7.8% CPU, max 282.5 Mb]

# Targets are stored.
readd(z)
#> [1] -0.08036404
```

<sup>Created on 2019-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by krlmlr** [comment] 2019-01-05 18:09
Thanks. Glancing at your example, I don't see where the dependencies x -> y and x -> z are defined. What am I missing?

**Comment by wlandau** [comment] 2019-01-05 18:13
They are resolved in `drake_config()`. `config$schedule` states the relationships among jobs.

**Comment by krlmlr** [comment] 2019-01-05 18:58
Does `drake_config()` parse the expressions then?

**Comment by wlandau** [comment] 2019-01-05 19:44
Yes it does, so maybe there is more to do. I may still recommend most people use `drake_config()`, but I will work on support for smaller custom `config` lists.

**Comment by wlandau** [comment] 2019-01-05 20:51
Update: I refactored `drake.hasty` so that you do not actually need to call `drake_config()`. The package no longer uses `drake`'s new backdoor (scheduler functions to the `parallelism` argument). To avoid the need for preprocessing, it has its own `hasty_make()` function instead. As long as you have the plan, the schedule, and an environment of functions, you are all set.

``` r
# Setup
library(drake.hasty) # https://github.com/wlandau/drake.hasty
#> Loading required package: drake
plan <- drake_plan(x = rnorm(100), y = mean(x), z = median(x))
config <- drake_config(plan)

# You do not actually need everything from `config`.
config <- config[c(
  "plan", # For the commands, which can be language objects.
  "schedule", # An igraph of the targets, which you can create yourself.
  "envir", # An environment with the functions that the commands use.
  "cache" # Only needed if you are using hasty_build_store.
          # You can create a storr cache yourself if you want.
)]

# Optionally activate clustermq for scheduling.
# (Otherwise, just run targets in a loop in topological order.)
config$jobs <- 2
options(clustermq.scheduler = "multicore")

# For each target, tell drake to run the command,
# store the value, and do nothing else.
config$hasty_build <- hasty_build_store

# Run the project.
hasty_make(config = config)
#> Warning: Hasty mode THROWS AWAY REPRODUCIBILITY to gain speed.
#> drake's scientific claims at
#>   https://ropensci.github.io/drake/#reproducibility-with-confidence
#>   are NOT VALID IN HASTY MODE!
#> Targets could be out of date even after make(),
#>   and you have no way of knowing.
#> USE AT YOUR OWN RISK!
#> Details: https://github.com/wlandau/drake.hasty/blob/master/README.md
#> Submitting 2 worker jobs (ID: 6655) ...
#> target x
#> target y
#> target z
#> Master: [0.2s 27.2% CPU]; Worker: [avg 7.1% CPU, max 268.7 Mb]

# Targets are cached.
readd(z)
#> [1] -0.0006174181
```

<sup>Created on 2019-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wlandau** [comment] 2019-01-05 21:08
I think `drake.hasty` now accomplishes all of what https://github.com/wlandau/workers was designed to do. A couple lingering questions:

1. I originally intended hasty mode to be a sandbox. Do we want to make it ready for serious use in production? If so, I can remove:
    1. The persistent warning about hasty mode, and
    2. The lingering uses of `:::` where the package borrows from `drake`'s internals.
2. What exactly would we gain by separating out `drake` into a package like `workers` or `drake.hasty`? The code that runs `drake` backends is actually very light and simple in comparison to everything else.

**Comment by krlmlr** [comment] 2019-01-05 21:47
Thanks. Are you suggesting to replace the code that calls `drake_config()` with a home-grown `config` object? What's a good way to come up with `config$schedule` ?

I'll try this next time I'm working with a large autogenerated dependency graph. Hope I can give better feedback by then.

**Comment by wlandau** [comment] 2019-01-05 23:46
Yeah, I think it would be nice to handle bare-bones use cases with smaller versions of `drake_config()` objects.

One simplifying assumption you suggested at `RStudio::conf(2018)` was that maybe all commands should be straightforward function calls. If each command is a call and each argument is a target, then you can grab the arguments, treat them as vertices on incoming edges, then call `igraph::graph_from_data_frame()` on a data frame of edges to create the schedule. Related: [`create_drake_graph()`](https://github.com/ropensci/drake/blob/master/R/preprocess-graph.R#L1).

To identify the dependencies of more complicated commands, `drake` used `codetools::findGlobals()` in the past, but it has since moved to an independent [`analyze_code()`](https://github.com/ropensci/drake/blob/master/R/preprocess-codeanalysis.R#L1) function. Maybe not the best thing for bare-bones workflows because of the overhead, though.

Do you think we can move this thread to the `drake.hasty` issue tracker, or should we keep it open in `drake` itself?

**Comment by wlandau** [comment] 2019-01-05 23:49
Maybe [`tidygraph`](https://github.com/thomasp85/tidygraph) could play a role here to, I don't know.

**Comment by krlmlr** [comment] 2019-01-05 23:57
Thanks. Any parsing here will be part of front-end code.

So, the `from` nodes are the dependencies, and the `to` nodes are the targets? And the names of the nodes are the target names?

**Comment by wlandau** [comment] 2019-01-06 00:53
Yes, exactly.

**Comment by wlandau** [comment] 2019-01-06 04:40
Also, I like that you suggested `crates` (re https://github.com/ropensci/drake/issues/575#issue-378223492). I think it is a great approach for transient workers (In fact, I believe `future` tries to carry out the same general idea of out shipping dependencies, even if the functions get to keep their closures.)

But for persistent workers, as in `drake.hasty` and `make(parallelism = "clustermq")`, it seems like we might risk sending multiple copies of the same data to the same workers. https://github.com/ropensci/drake/issues/561#issuecomment-433642782 may help `drake` gain efficiency in this area.

**Comment by wlandau** [comment] 2019-01-06 04:41
Closing this issue in favor of https://github.com/wlandau/drake.hasty/issues/1 and https://github.com/wlandau/drake.hasty/issues/2. This has been a great discussion so far, and I think we can continue it there.

**Closed by wlandau** 2019-01-06 04:41 UTC
Labels: difficulty: hard :fire:, topic: API :door:, topic: performance :checkered_flag:

**Comment by wlandau** [comment] 2019-01-06 19:14
@krlmlr by the way, `drake` is going to get better at handling the large workflows that motivated `drake.hasty`. In #647, I identified several large bottlenecks, most of which I think we can remove. I would have addressed these bottlenecks sooner, but https://github.com/rstudio/profvis/issues/104 was giving me trouble.

**Comment by wlandau** [comment] 2020-02-24 01:20
FYI: I just wrote a design spec for `drake`: Now implemented: https://github.com/ropensci-books/drake/blob/master/design.Rmd
