### ISSUE TITLE
Lock file permission issues

### ISSUE THREAD

**Issue by pydupont** [ropensci/drake#1239] opened 2020-04-14 02:14 UTC
Hello,

On a Linux machine if a user runs a drake pipeline, the same pipeline can't be run again (or the results checked) by another user. The following error occurs:

```
Error in filelock::lock(private$lock_file) : 
  Cannot open lock file: Permission denied
Error in filelock::unlock(lock) : 
  VECTOR_ELT() can only be applied to a 'list', not a 'closure'
```

If the  file `.drake/drake/history/lock` is removed manually, the second user can use the pipeline again.

Is there a way to unlock the pipeline from R?
I used the option `lock_envir = FALSE` in the make function but the problem is still occurring.

I am using drake v7.7.0.9002 with R3.5.1

Is this the same issue as #1232? I would prefer to keep the history, so do I have a solution that doesn't require me setting `history = FALSE`.
Shouldn't the lock file be removed if the pipeline is finished?

Kindly,

Pierre

**Comment by wlandau** [comment] 2020-04-14 12:12
Yes, it is the same issue as #1232. Unfortunately, the best I can recommend is to remove the lockfile or disable history. Maybe this should be addressed in the `filelock` package itself.

**Comment by wlandau** [comment] 2020-04-14 17:35
You could also try and install https://github.com/wlandau/txtq/commit/ba15026515887591c02461bb9b436273a460b591. That commit forces `txtq` to remove the lockfile periodically. It should solve this issue except if the `drake` session crashes at the wrong time and does not clean up.

**Comment by wlandau** [comment] 2020-04-14 17:52
Hmm... that turns out to not work on Windows for some reason. Try https://github.com/wlandau/txtq/commit/4bf88769facacbcf9f2350831824c6b086e6450c. In that commit, the lockfile is created in advance and outside `filelock`, which just might resolve permissions issues. I don't know.

**Comment by pydupont** [comment] 2020-04-14 21:38
None of the two `txtq` commits solved the problem. I also updated `drake` to the last version on github but still no success. I will have a look at `filelock`.
Cheers

**Comment by pydupont** [comment] 2020-04-14 22:06
Would it be possible to change the permissions on the lock file using:
```R
Sys.chmod(".drake/drake/history/lock", "660", use_umask = FALSE)
```
So that people from the same user group can use the lock file too?

**Comment by wlandau** [comment] 2020-04-14 23:54
Possible, yes, but not something I am likely to do in drake itself. I recommend invoking it in your script(s) that invoke drake, and posting an issue to filelock if you can reproduce the issue without drake or txtq.

**Comment by wlandau** [comment] 2020-04-22 03:57
`drake` does not actually need `txtq` to have a lock file because only the master process modifies history. So https://github.com/ropensci/drake/issues/1232 will probably open up a better solution.

**Comment by wlandau** [comment] 2020-04-23 12:25
Closing again due to https://github.com/wlandau/txtq/issues/18#issuecomment-618371802. Sorry to have gotten your hopes up.

**Closed by wlandau** 2020-04-23 12:25 UTC
Labels: status: duplicate, type: trouble

**Comment by wlandau** [comment] 2020-06-23 00:32
From https://github.com/r-lib/filelock/issues/26, it looks like this error came from the fact that some file systems do not support file locking. Should be fixed for `drake` in 2ffd42af9d9d14f8f1e9482eee03bc24bfbdbb7b. Feel free to give it a try.

**Comment by pydupont** [comment] 2020-06-23 04:24
It works! Thanks for your work!

**Comment by wlandau** [comment] 2020-06-23 10:12
Thanks for confirming.
