### ISSUE TITLE
`r_make()` does not pick up changes in from `knitr_in()` 

### ISSUE THREAD

**Issue by pat-s** [ropensci/drake#887] opened 2019-05-27 14:50 UTC
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.
- [x] Advanced users: verify that the bug still persists in the current development version (i.e. `remotes::install_github("ropensci/drake")`) and mention the [SHA-1 hash](https://git-scm.com/book/en/v1/Getting-Started-Git-Basics#Git-Has-Integrity) of the [Git commit you install](https://github.com/ropensci/drake/commits/master).

## Description

When changing the dependencies of an Rmarkdown report tracked with `knitr_in()`, `r_make()` (and the manual way sourcing the config) _sometimes_ do not pick up the following changes to dependencies loaded with `drake::loadd()`:

- changes to object names
- commented/uncommented objects

This sounds in the first place like a trigger related problem.
However, this happens in an inconsistent fashion, i.e. the behavior is not persistent across the above mentioned actions.
Neither it is persistent across R sessions.
I've tried to find a reproducible pattern but was not successful.

A reprex seems to be complicated here since I can't interactively change the object name and then source the config again.
It could be related to triggers?
But I would expect that changing object names of dependencies of a report file changes the hash of the drake target. 

## Reproducible example

Not available.

## Environment

Tested on v7.2.0 but I see no possible related changes to `knitr_in()` in the latest release.

## Expected output

Changes of dependency object names in Rmarkdown reports get picked up by _drake_.

**Comment by wlandau** [comment] 2019-05-27 15:12
I think this is because the processing steps in drake_config() are memoized (see create_drake_layout()). What this means is that some dependency checks are skipped if drake thinks they do not need to be repeated. If I am right, all we need to do is memoize against the relevant knitr / R Markdown source files. I will take a look tonight.

**Comment by wlandau** [comment] 2019-05-27 21:31
A reprex:

```` r
library(drake)
  plan <- drake_plan(
  a = TRUE,
  b = TRUE,
  report_step = knitr_in("report.Rmd")
)

# Two versions of the report.
lines_a <- c(
  "---",
  "title: abc",
  "---",
  "",
  "```{r}",
  "readd(a)",
  "```"
)
lines_b <- c(
  "---",
  "title: abc",
  "---",
  "",
  "```{r}",
  "readd(b)",
  "```"
)

# Compute the DAG on the first report.
writeLines(lines_a, "report.Rmd")
cache <- storr::storr_environment()
for (i in 1:2) {
  config <- drake_config(
    plan,
    cache = cache,
    session_info = FALSE
  )
}
vis_drake_graph(config)
````

![](https://i.imgur.com/IrVbC5S.png)

``` r

# drake does not recompute the DAG
# when the report has different dependencies.
writeLines(lines_b, "report.Rmd")
config <- drake_config(
  plan,
  cache = cache,
  session_info = FALSE
)

# The report step should depend on `b`, not `a`.
vis_drake_graph(config)
```

![](https://i.imgur.com/m1D43gk.png)

<sup>Created on 2019-05-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment] 2019-05-27 22:34
Yup, it was the memoization. Patch coming soon.

**Comment by wlandau** [comment] 2019-05-27 22:39
Now fixed.

**Comment by pat-s** [comment] 2019-05-28 07:28
Thanks for the instant fix, works like a charm!
Impressive that you even came up with a reprex for this non-trivial case. :rocket:

**Comment by wlandau** [comment] 2019-05-28 12:00
Thanks.

I may have actually introduced a bug, so I am reopening this. I need to check what happens if the knitr files are missing.

**Comment by wlandau** [comment] 2019-05-28 12:18
Reproduced, fixed, and tested in https://github.com/ropensci/drake/commit/8adaee92f2d6e5e3e7fbd4471b74e8a3e728130e.

**Closed** 2019-05-28 12:17 UTC
Labels: topic: reproducibility, type: bug
